version: '3'

services:
  my-scala-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SQLITE_DB_PATH=/home/app/sqlite-dir/localdatabase.db
